Server
loyd/greeder pull request #23
Opened 2017-04-28 07:44 UTC by yandzee

Close #4, #5, #6, #7, #8, #13

2017-04-28 07:47 UTC, loyd commented
Ok не глядя

2017-04-28 09:23 UTC, loyd requested changes

2017-04-28 09:23 UTC, loyd commented on common/types.rs
> +        serializer.serialize_str(key_str.as_str())
Не надо аллоцировать промежуточную строку, просто:
```js
serializer.serialize_str(self.as_ref());
```

2017-04-28 09:23 UTC, loyd commented on common/types.rs
> +        serializer.serialize_str(key_str.as_str())
И тут

2017-04-28 09:23 UTC, loyd commented on server/Cargo.toml
> +default-features = true
Верни назад и добавь нужную в `features` ниже

2017-04-28 09:23 UTC, loyd commented on server/controllers/entry.rs
> +#[get("/<entry_id>")]
Мы не используем публично `entry.id`, только `entry.key`:
1. Его сложно перебирать
2. С key получаем ЧПУ
3. Можно вакуумизировать базу.

2017-04-28 09:23 UTC, loyd commented on server/controllers/entry.rs
> +    let conn = conn.lock().unwrap();
ниже импортов

2017-04-28 09:23 UTC, loyd commented on server/controllers/entry.rs
> +        Err(_) => return Template::render("error", &EmptyContext)
Просто `Template::render("error", ())`

2017-04-28 09:23 UTC, loyd commented on server/controllers/entry.rs
> +        Err(_) => return Template::render("error", &EmptyContext)
Просто `Template::render("error", ())`

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +    let mut socket = match UnixDatagram::bind("./fetcher") {
Давай-ка лучше UDP использовать будем.

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +    Custom(Status::Ok, JSON(feeds))
Нет, давай из ручки возвращать `Result<JSON, Custom>`

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +    use schema::feed::dsl::id;
use наверх

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +        let part = feed::table
JOIN

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +        feeds.extend(part);
Нет, весь цикл нужно поменять на `subscriptions.into_inter().flat_map(...).collect()`

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +    uid: String,
`&'a str`?

2017-04-28 09:23 UTC, loyd commented on server/controllers/feed.rs
> +// pub fn remove(feed: JSON<Feed>) {
Закомментированный код? Лолщито?

2017-04-28 09:23 UTC, loyd commented on server/controllers/index.rs
> +type IoResult<T> = io::Result<T>;
`use std::io::Result as IoResult;`

2017-04-28 09:23 UTC, loyd commented on server/controllers/index.rs
> +use std::io;
По растовому кодстайлу сначала идут инклюды std, потом внешние, потом \n, потом локальные

2017-04-28 09:23 UTC, loyd commented on server/controllers/index.rs
> +}
\n

2017-04-28 09:23 UTC, loyd commented on server/controllers/index.rs
> +fn statics(file: PathBuf) -> Option<NamedFile> {
Отгружать статику на сервер нужно (поправь `rctl`)

2017-04-28 09:23 UTC, loyd commented on server/controllers/management.rs
> +    uid: String
`&'a str`?

2017-04-28 09:23 UTC, loyd commented on server/controllers/management.rs
> +    Custom(Status::Ok, JSON(FeedNSubs {
Result

2017-04-28 09:23 UTC, loyd commented on server/controllers/management.rs
> +}
\n

2017-04-28 09:23 UTC, loyd commented on server/models.rs
> +                // ts.sec + (ts.nsec / 1000000000) as i64
srsly?

2017-04-28 09:23 UTC, loyd commented on server/models.rs
> +                strftime("%d.%m.%Y %H:%M", &tm).unwrap()
Эта логика должна быть во вью (в нашем случае в презенторе), а не в модели

2017-04-28 09:23 UTC, loyd commented on server/static/js/feed.js
> +	return http.get('/feed/entries/'+entryId).then(r => r.data);
Используй `fetch`, luke

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +class http {
Это не класс, а модуль.

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +class http {
Выкинь и используй fetch.

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +			.filter(line => line.trim().length > 0)
Два раза трим делаешь

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +			.map(gluedHeader => gluedHeader.split(':').map(part => part.trim()))
split сломается, если будет несколько `:`

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +			.map(gluedHeader => gluedHeader.split(':').map(part => part.trim()))
И да, заголовки надо в lowercase

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +				return Object.assign(acc, { [pair[0]]: pair[1] })
return?

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +			.reduce((acc, pair) => {
`(acc, [name, value])`

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +		let xhr = new XMLHttpRequest();
`const`

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +	static request(method, addr, params, headers) {
`headers = {}`

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +		return new Promise((resolve, reject) => {
Почему везде табы?

2017-04-28 09:23 UTC, loyd commented on server/static/js/http.js
> +					headers: headers
shortend-ы

2017-04-28 09:23 UTC, loyd commented on server/static/js/index.js
> +	console.log(feeds);
`console.log`, 10/10

2017-04-28 09:23 UTC, loyd commented on server/static/js/index.js
> +	console.error(e);
15/10

2017-04-28 09:23 UTC, loyd commented on server/static/js/templater.js
> +		let completion = this.text;
`const`, табы

2017-04-28 09:23 UTC, loyd commented on server/static/js/templater.js
> +class Templator {
Шаблонизируемся на сервере

2017-05-04 11:52 UTC, yandzee commented on server/controllers/feed.rs
> +        let part = feed::table
непонятно как его адекватно сделать с diesel'ем

2017-05-04 12:15 UTC, yandzee commented on server/controllers/feed.rs
> +        feeds.extend(part);
Тогда я оттуда ошибку не выброшу из ручки

2017-05-04 15:21 UTC, loyd commented on server/controllers/feed.rs
> +        feeds.extend(part);
Ну, вообще-то можно, ибо есть `impl<A, E, V> FromIterator<Result<A, E>> for Result<V, E> `. Но ладно, сойдёт и так.

2017-05-04 19:07 UTC, yandzee commented on server/static/js/http.js
> +class http {
и так сойдет

2017-05-04 19:07 UTC, yandzee commented on server/static/js/http.js
> +			.map(gluedHeader => gluedHeader.split(':').map(part => part.trim()))
похер

2017-05-04 19:07 UTC, yandzee commented on server/static/js/http.js
> +			.reduce((acc, pair) => {
похер

2017-05-04 19:07 UTC, yandzee commented on server/static/js/http.js
> +				return Object.assign(acc, { [pair[0]]: pair[1] })
похер

2017-05-04 19:07 UTC, yandzee commented on server/static/js/http.js
> +	static request(method, addr, params, headers) {
похер

2017-05-04 19:08 UTC, yandzee commented on server/static/js/http.js
> +		let xhr = new XMLHttpRequest();
похер

2017-05-04 19:08 UTC, yandzee commented on server/static/js/http.js
> +		return new Promise((resolve, reject) => {
похер

2017-05-04 19:08 UTC, yandzee commented on server/static/js/http.js
> +					headers: headers
похер

2017-05-04 19:08 UTC, yandzee commented on server/static/js/index.js
> +	console.log(feeds);
xD

2017-05-04 19:08 UTC, yandzee commented on server/static/js/index.js
> +	console.error(e);
похер

2017-05-04 19:08 UTC, yandzee commented on server/static/js/templater.js
> +class Templator {
да, выкинул его

2017-05-04 19:08 UTC, yandzee commented on server/static/js/templater.js
> +		let completion = this.text;
похер

2017-05-04 19:10 UTC, yandzee commented
все четко, почти все исправил

2017-05-04 22:36 UTC, loyd commented
lgtm

2017-05-05 06:03 UTC, loyd approved these changes

2017-05-05 06:03 UTC, merged